local v1 = { CFrame.new(0, 0, 0) * CFrame.Angles(0, -math.pi / 2, 0), CFrame.new(0, 0, 0) * CFrame.Angles(0, math.pi / 2, 0), CFrame.new(0, 0, 0) * CFrame.Angles(0, math.pi, 0), CFrame.new(0, 0, 0) * CFrame.Angles(0, 0, 0) };

return {
	Dirt = {
		hardness = .5,
		drop = "Dirt",
		hasItsOwnItem = true,
		betterTool = "shovel", 
		material = "dirt",
	},
	GrassBlock = {
		hardness = .6,
		drop = "Dirt",
		hasItsOwnItem = "Grass Block",
		betterTool = "shovel", 
		material = "grass",
		texture = {
			[Enum.NormalId.Top] = "grasstop",
			[Enum.NormalId.Front] = "grassside", 
			[Enum.NormalId.Left] = "grassside", 
			[Enum.NormalId.Right] = "grassside", 
			[Enum.NormalId.Back] = "grassside", 
			[Enum.NormalId.Bottom] = "dirt",
		}
	},
	Door = {
		hardness = 3, 
		drop = "Door", 
		betterTool = "axe", 
		blocktype = "hollow", 
		material = "wood", 
		custom = "Door", 
		facingPos = {
			CFrame.new(1.35, 0, 0) * CFrame.Angles(0, -math.pi / 2, 0), 
			CFrame.new(-1.35, 0, 0) * CFrame.Angles(0, math.pi / 2, 0), 
			CFrame.new(0, 0, 1.35) * CFrame.Angles(0, math.pi, 0), 
			CFrame.new(0, 0, -1.35)
		}
	},
	Sand = {
		hardness = .5,
		drop = "Sand",
		hasItsOwnItem = true,
		material = "sand",
		betterTool = "shovel", 
	},
	Water = {
		hardness = 100,
		hasItsOwnItem = true,
		blocktype = "fluid",
		material = "water",
	},
	Lava = {
		hardness = 100,
		hasItsOwnItem = true,
		blocktype = "fluid",
		material = "lava",
	},
	Bedrock = {
		hardness = 9.223372e+18,
		hasItsOwnItem = true,
		drop = "Stone",
		material = "stone",
	},
	Stone = {
		hardness = 1.5,
		drop = "Cobblestone",
		toolRequire = "pickaxe",
		hasItsOwnItem = true,
		material = "stone",
	},
	Cobblestone = {
		hardness = 1.5,
		drop = "Cobblestone",
		toolRequire = "pickaxe",
		hasItsOwnItem = true,
		material = "stone",
	},
	Leaves = {
		hardness = 0.3,
		hasItsOwnItem = true,
		betterTool = "shears",
		toolLevelRequire = "shears",
		raredrop = {
			{1/20,"Stick"},
		},
		material = "leaves",
	},
	OakLog = {
		hardness = 2,
		drop = "OakLog",
		hasItsOwnItem = "Log",
		betterTool = "axe",
		material = "wood",
	},
	OakPlanks = {
		hardness = 2,
		drop = "OakPlanks",
		hasItsOwnItem = "Planks",
		betterTool = "axe",
		material = "wood",
	},
	CraftingTable = {
		hardness = 2,
		drop = "CraftingTable",
		hasItsOwnItem = "Crafting Table",
		betterTool = "axe",
		material = "wood",
		facingPos = v1
	},
	Furnace = {
		hardness = 3.5,
		drop = "Furnace",
		hasItsOwnItem = "Furnace",
		toolRequire = "pickaxe",
		material = "stone",
		facingPos = v1
	},
	Glass = {
		hardness = .3,
		hasItsOwnItem = true,
		material = "glass",
	},
	CoalOre = {
		hardness = 3,
		drop = "Coal",
		toolRequire = "pickaxe",
		toolLevelRequire = "wooden",
		hasItsOwnItem = "Coal Ore",
		material = "stone",
	},
	GoldOre = {
		hardness = 3,
		drop = "GoldOre",
		toolRequire = "pickaxe",
		toolLevelRequire = "iron",
		hasItsOwnItem = "Gold Ore",
		material = "stone",
	},
	IronOre = {
		hardness = 3,
		drop = "IronOre",
		toolRequire = "pickaxe",
		toolLevelRequire = "stone",
		hasItsOwnItem = "Iron Ore",
		material = "stone",
	},
	DiamondOre = {
		hardness = 3,
		drop = "Diamond",
		toolRequire = "pickaxe",
		toolLevelRequire = "iron",
		hasItsOwnItem = "Diamond Ore",
		material = "stone",
	},
	CoalBlock = {
		hardness = 5,
		drop = "CoalBlock",
		toolRequire = "pickaxe",
		toolLevelRequire = "stone",
		hasItsOwnItem = "Coal Block",
		material = "metal",
	},
	IronBlock = {
		hardness = 5,
		drop = "IronBlock",
		toolRequire = "pickaxe",
		toolLevelRequire = "stone",
		hasItsOwnItem = "Iron Block",
		material = "metal",
	},
	GoldBlock = {
		hardness = 5,
		drop = "GoldBlock",
		toolRequire = "pickaxe",
		toolLevelRequire = "iron",
		hasItsOwnItem = "Gold Block",
		material = "metal",
	},
	DiamondBlock = {
		hardness = 5,
		drop = "DiamondBlock",
		toolRequire = "pickaxe",
		toolLevelRequire = "iron",
		hasItsOwnItem = "Diamond Block",
		material = "metal",
	},
	Obsidian = {
		hardness = 50,
		drop = "Obsidian",
		toolRequire = "pickaxe",
		toolLevelRequire = "diamond",
		hasItsOwnItem = true,
		material = "stone",
	},
	Torch = {
		hardness = 0,
		drop = "Torch",
		blocktype = "nonsolid",
		facingPos = {
			CFrame.new(-1.3,0,0) * CFrame.Angles(0,0,math.rad(-15)),
			CFrame.new(1.3,0,0) * CFrame.Angles(0,0,math.rad(15)),
			CFrame.new(0,0,-1.3) * CFrame.Angles(math.rad(15),0,0),
			CFrame.new(0,0,1.3) * CFrame.Angles(math.rad(-15),0,0),
			CFrame.new(0,-0.5675,0)
		},
		facingPosDef = 5,
		custom = "Torch",
	}
}
